### ISSUE TITLE
Serialization compatibility with the Rust implementation

### ISSUE THREAD

**Issue by danwallach** [votingworks/electionguard-kotlin-multiplatform#107]
Dependent issue: https://github.com/microsoft/electionguard-python/issues/646

Depending on what they do or don't fix, we might need to:
- Ensure that we're always serializing integers to 32-bits
- Remove the 0x00 from the KDF computation
- Encode HMAC keys in hex bytes (hopefully not!)

We should also double-check that we (and they) are correctly handling inputs that aren't multiples of 32 bytes long. (Took some extra effort to get this correct in the TypeScript code.)

**Comment by JohnLCaron** [comment]
When C++ and kotlin are at the same serialization version, presumably 2.0, we will wantt o check compatibility of implementations with the spec.
Anticipating that the spec will use JSON.

**Comment by danwallach** [comment]
Serialization compatibility is going to be a broad issue for us, not just in the hash cipher thing, although that specific function is one of many places where we need to be bug for bug compatible, else it just doesn't work.

**Comment by JohnLCaron** [comment]
We are waiting for the 2.0 spec before worrying too much about this. When its out, we can test compatibility with c++ library.

My thinking is that we will keep our protobuf based classes as central, and have CLI that transform back and forth to JSON.

Also notable is that the webapps use JSON to communicate to remote guardians. These structure include many of the primitives used in the election record. So we already have that done as a template for the rest of the classes.

**Comment by JohnLCaron** [comment]
PR #222 adds json serialization of Manifest for version 1.52, and tests against proto serialization.

**Comment by JohnLCaron** [comment]
PR #223 adds json serialization for most of the other classes. Need the spec and C++ examples to finish.

**Comment by JohnLCaron** [comment]
Waiting to hear from Rust implementation, which is doing the 2.0 implementration.

**Comment by JohnLCaron** [comment]
Superceeded by Issue #373
