### ISSUE TITLE
Overvote handling

### ISSUE THREAD

**Issue by danwallach** [votingworks/electionguard-kotlin-multiplatform#156]
The spec now has overvote interpretation (p. 21). We're supposed to conventionally encrypt a byte array that includes the original voter intent. This byte array also needs to include write-in strings. 

See also, page 20, and the variable $b_D$, which specifies some multiple of 32 bytes.

**Comment by danwallach** [comment]
This means that an overvoted ballot is no longer "invalid" when it's encrypted.

**Comment by JohnLCaron** [comment]
Also see #155

**Comment by JohnLCaron** [comment]
Have some PRs to implement this.
Also see issue #155

**Comment by JohnLCaron** [comment]
This needs work, now that the spec is more or less done.

**Comment by JohnLCaron** [comment]
See spec 2.0 3.1.3 paragraph **Overvotes**

**Comment by JohnLCaron** [comment]
Not invalidating ballot because of overvote on one selection.
